<template>
  <v-container>
    <v-row class="text-center">
      <v-col cols="12">
        <v-img
            :src="require('../assets/logo.svg')"
            class="my-3"
            contain
            height="200"
        />
      </v-col>

      <v-col class="mb-4">
        <h1 class="display-2 font-weight-bold mb-3">
          Welcome to WorldNews
        </h1>

        <p class="subheading font-weight-regular">
          You will need to read some news and vote if they are real, or they have been generated by AI.
          <br>If you believe that the news is real, and you even find some evidence, add the urls to sources in the
          voting section.
        </p>
      </v-col>

      <v-col
          class="mb-5"
          cols="12"
      >
        <h2 class="headline font-weight-bold mb-3">
          Great News!
        </h2>

        <v-card v-for="item in news.slice(0, amount)" :key="item.article" class="mx-auto" outlined>
          <v-list-item three-line>
            <v-list-item-content>
              <div class="text-overline mb-4">
                {{ getKeyWords(item.keyWords) }}
              </div>
              <v-list-item-title class="text-h5 mb-1">
                {{ item.article }}
              </v-list-item-title>
              <v-list-item-subtitle>{{ item.text }}</v-list-item-subtitle>
            </v-list-item-content>

            <v-list-item-avatar
                tile
                size="125"
                color="grey"
            ><v-img :src="item.preview"></v-img></v-list-item-avatar>
          </v-list-item>

          <v-card-actions>
            <v-btn
                outlined
                rounded
                text
                class="mt-4"
                :href="'/news/' + item.id"
            >
              Read more
            </v-btn>
          </v-card-actions>
        </v-card>

        <v-btn
            outlined
            rounded
            text
            class="mt-4"
            @click="amount += 5"
            v-if="amount < news.length"
        >
          Get more news
        </v-btn>

      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  name: 'HelloWorld',

  data() {
    return {
      amount: 5
    }
  },

  created() {
    this.$store.dispatch('news/getAll');
  },

  methods: {

    getKeyWords(word) {
      let outism = '';
      word.map((el) => {
        outism += el + ', ';
      })
      return outism.substring(0, outism.length - 2)
    }
  },

  computed: {
    news() {
      return this.$store.state.news.all.news;
    }

  }
}
</script>
